apiVersion: apps/v1
kind: Deployment
metadata:
  name: hy-project
  labels:
    app: hy-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hy-project
  template:
    metadata:
      labels:
        app: hy-project
    spec:
      containers:
      - name: hy-project 
        image: bshrramadan/log-output
        ports:
        - containerPort: 80
        imagePullPolicy: IfNotPresent
